import { NextResponse } from 'next/server'
import { getPayload } from 'payload'
import configPromise from '@payload-config'
import { iyzipay } from '@/lib/iyzico'

const initializeCheckoutForm = (request: any): Promise<any> => {
  return new Promise((resolve, reject) => {
    iyzipay.checkoutFormInitialize.create(request, (err: any, result: any) => {
      if (err) return reject(err);
      resolve(result);
    });
  });
};

export async function POST(req: Request) {
  try {
    const data = await req.json()
    const { customerInfo, items, totalAmount } = data

    if (!customerInfo || !items || items.length === 0) {
      return NextResponse.json({ success: false, error: 'Eksik bilgi gönderildi' }, { status: 400 })
    }

    const payload = await getPayload({ config: configPromise })

    // Create the order in Payload CMS
    const order = await payload.create({
      collection: 'orders',
      data: {
        orderNumber: '', // will be auto-generated by hook
        customerInfo: {
          firstName: customerInfo.firstName,
          lastName: customerInfo.lastName,
          email: customerInfo.email,
          phone: customerInfo.phone,
          address: customerInfo.address,
          district: customerInfo.district,
          isCorporate: customerInfo.isCorporate || false,
          companyName: customerInfo.companyName,
          taxOffice: customerInfo.taxOffice,
          taxNumber: customerInfo.taxNumber,
        },
        orderItems: items.map((item: any) => ({
          product: typeof item.id === 'number' || (typeof item.id === 'string' && !isNaN(Number(item.id))) ? Number(item.id) : null,
          quantity: item.quantity,
          price: parseInt(String(item.price).replace(/[^0-9]/g, '')) || 0,
        })),
        totalAmount: totalAmount,
        status: 'pending',
        paymentStatus: 'unpaid',
      },
    })

    // Prepare Iyzico Request
    const host = req.headers.get('origin') || process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000';
    
    const request = {
      locale: 'tr',
      conversationId: order.orderNumber, // hook tarafından oluşturulan numara
      price: totalAmount.toString(),
      paidPrice: totalAmount.toString(),
      currency: 'TRY',
      basketId: order.id.toString(),
      paymentGroup: 'PRODUCT',
      callbackUrl: `${host}/api/checkout/callback`,
      enabledInstallments: [2, 3, 6, 9],
      buyer: {
        id: 'BY789',
        name: customerInfo.firstName || 'Bilinmiyor',
        surname: customerInfo.lastName || 'Bilinmiyor',
        gsmNumber: customerInfo.phone,
        email: customerInfo.email,
        identityNumber: (customerInfo.isCorporate && customerInfo.taxNumber) ? customerInfo.taxNumber : '11111111111', 
        lastLoginDate: '2023-10-05 12:43:35',
        registrationDate: '2023-04-21 15:12:09',
        registrationAddress: `${customerInfo.district} - ${customerInfo.address}`,
        ip: '85.34.78.112',
        city: 'Istanbul',
        country: 'Turkey',
        zipCode: '34732'
      },
      shippingAddress: {
        contactName: `${customerInfo.firstName} ${customerInfo.lastName}`,
        city: 'Istanbul',
        country: 'Turkey',
        address: `${customerInfo.district} - ${customerInfo.address}`,
        zipCode: '34742'
      },
      billingAddress: {
        contactName: customerInfo.isCorporate ? customerInfo.companyName : `${customerInfo.firstName} ${customerInfo.lastName}`,
        city: 'Istanbul',
        country: 'Turkey',
        address: `${customerInfo.district} - ${customerInfo.address}`,
        zipCode: '34742'
      },
      basketItems: items.map((item: any) => ({
        id: item.id.toString(),
        name: item.name,
        category1: 'Pastane',
        itemType: 'PHYSICAL',
        price: (parseInt(String(item.price).replace(/[^0-9]/g, '')) || 0).toString()
      }))
    };

    const result = await initializeCheckoutForm(request);

    if (result.status === 'success') {
      return NextResponse.json({ 
        success: true, 
        orderNumber: order.orderNumber,
        checkoutFormContent: result.checkoutFormContent,
        paymentPageUrl: result.paymentPageUrl
      })
    } else {
      console.error("Iyzico Error:", result);
      return NextResponse.json({ success: false, error: result.errorMessage }, { status: 400 })
    }

  } catch (error: any) {
    console.error('Checkout error:', error)
    return NextResponse.json({ success: false, error: error.message }, { status: 500 })
  }
}
