import { NextResponse } from 'next/server'
import { getPayload } from 'payload'
import configPromise from '@payload-config'

export async function POST(req: Request) {
  try {
    const data = await req.json()
    const { customerInfo, items, totalAmount } = data

    if (!customerInfo || !items || items.length === 0) {
      return NextResponse.json({ success: false, error: 'Eksik bilgi gönderildi' }, { status: 400 })
    }

    const payload = await getPayload({ config: configPromise })

    // Create the order in Payload CMS
    const order = await payload.create({
      collection: 'orders',
      data: {
        orderNumber: '', // will be auto-generated by hook
        customerInfo: {
          name: customerInfo.name,
          email: customerInfo.email,
          phone: customerInfo.phone,
          address: customerInfo.address,
        },
        orderItems: items.map((item: any) => ({
          product: typeof item.id === 'string' && item.id.includes('-') ? null : item.id, // Handles non-db products if any
          quantity: item.quantity,
          price: parseInt(String(item.price).replace(/[^0-9]/g, '')) || 0,
        })),
        totalAmount: totalAmount,
        status: 'pending',
        paymentStatus: 'unpaid',
      },
    })

    try {
      await payload.sendEmail({
        to: 'siparis@dilim.com', // Değiştirilebilir
        from: 'sistem@dilim.com', // Değiştirilebilir
        subject: `Yeni Sipariş: ${order.orderNumber} - ${customerInfo.name}`,
        html: `
          <div style="font-family: sans-serif; line-height: 1.5; color: #333;">
            <h2 style="color: #FF8A00;">Yeni Sipariş Alındı (Sipariş No: ${order.orderNumber})</h2>
            <p>Sistem üzerinden yeni bir sipariş oluşturuldu.</p>
            
            <h3 style="border-bottom: 1px solid #eee; padding-bottom: 5px;">Müşteri Bilgileri</h3>
            <p><strong>Ad Soyad:</strong> ${customerInfo.name}</p>
            <p><strong>Telefon:</strong> ${customerInfo.phone}</p>
            <p><strong>E-posta:</strong> ${customerInfo.email || 'Belirtilmedi'}</p>
            <p><strong>Teslimat Adresi:</strong> ${customerInfo.address}</p>
            
            <h3 style="border-bottom: 1px solid #eee; padding-bottom: 5px;">Sipariş Detayları</h3>
            <ul>
              ${items.map((item: any) => `<li>${item.quantity}x ${item.name} - ${item.price}</li>`).join('')}
            </ul>
            <p style="font-size: 18px;"><strong>Toplam Tutar:</strong> ${totalAmount} ₺</p>
            
            <p style="margin-top: 20px;">
              <a href="http://localhost:3000/admin/collections/orders/${order.id}" style="background-color: #000; color: #fff; padding: 10px 20px; text-decoration: none; border-radius: 5px;">Yönetim Panelinde Görüntüle</a>
            </p>
          </div>
        `
      })
    } catch (emailErr) {
      console.log('E-posta gönderimi başarısız:', emailErr)
    }

    return NextResponse.json({ 
      success: true, 
      orderNumber: order.orderNumber,
      message: 'Sipariş başarıyla oluşturuldu'
    })

  } catch (error: any) {
    console.error('Checkout error:', error)
    return NextResponse.json({ success: false, error: error.message }, { status: 500 })
  }
}
