import { NextRequest, NextResponse } from 'next/server'
import { getPayload } from 'payload'
import configPromise from '@payload-config'
// import { iyzipay } from '@/lib/iyzico'
import { getServerSession } from "next-auth/next"
import { authOptions } from "@/lib/auth"

export const maxDuration = 60;

const initializeCheckoutForm = async (request: any): Promise<any> => {
  const { iyzipay } = await import('@/lib/iyzico');
  return new Promise((resolve, reject) => {
    try {
      iyzipay.checkoutFormInitialize.create(request, (err: any, result: any) => {
        if (err) return reject(err);
        resolve(result);
      });
    } catch (err) {
      reject(err);
    }
  });
};

export async function POST(req: Request) {
  try {
    const data = await req.json()
    const { customerInfo, items, totalAmount, couponCode } = data

    if (!customerInfo || !items || items.length === 0) {
      return NextResponse.json({ success: false, error: 'Eksik bilgi gönderildi' }, { status: 400 })
    }

    const payload = await getPayload({ config: configPromise })

    // Verify prices from the database
    let calculatedTotal = 0;
    const validatedItems = [];

    for (const item of items) {
      const productId = typeof item.id === 'number' || (typeof item.id === 'string' && !isNaN(Number(item.id))) ? Number(item.id) : null;
      if (!productId) {
        return NextResponse.json({ success: false, error: 'Geçersiz ürün ID' }, { status: 400 });
      }

      try {
        const product = await payload.findByID({
          collection: 'products',
          id: productId,
        });

        if (!product) {
          return NextResponse.json({ success: false, error: 'Ürün bulunamadı' }, { status: 400 });
        }

        const quantity = parseInt(item.quantity) || 1;
        const unitPrice = product.price || 0;
        calculatedTotal += unitPrice * quantity;

        validatedItems.push({
          id: item.id.toString(),
          name: product.title || item.name,
          quantity: quantity,
          productId: productId,
          realUnitPrice: unitPrice,
          realLineTotal: unitPrice * quantity,
          options: item.options || '',
        });
      } catch (err) {
        return NextResponse.json({ success: false, error: 'Ürün bilgisi alınamadı' }, { status: 400 });
      }
    }

    // Eğer kupon kodu geldiyse veritabanından doğrula
    let discountAmount = 0;
    if (couponCode) {
      const couponRes = await payload.find({
        collection: 'coupons',
        where: { code: { equals: couponCode } }
      });
      
      if (couponRes.totalDocs > 0) {
        const coupon = couponRes.docs[0];
        if (coupon.isActive && 
           (!coupon.expiryDate || new Date(coupon.expiryDate) >= new Date()) && 
           (!coupon.minimumCartValue || calculatedTotal >= coupon.minimumCartValue)) {
             
             if (coupon.discountType === 'percentage') {
               discountAmount = (calculatedTotal * coupon.discountValue) / 100;
             } else {
               discountAmount = coupon.discountValue;
             }
        }
      }
    }

    const finalCalculatedTotal = Math.max(0, calculatedTotal - discountAmount);

    if (finalCalculatedTotal !== totalAmount) {
      return NextResponse.json({ success: false, error: 'Sepet tutarı uyuşmuyor. Lütfen sayfanızı yenileyin.' }, { status: 400 });
    }

    // Müşteri oturumu var mı kontrol et
    const session = await getServerSession(authOptions);
    let customerId = null;

    if (session?.user?.email) {
      const users = await payload.find({
        collection: 'customers',
        where: { email: { equals: session.user.email } }
      });
      if (users.docs.length > 0) {
        customerId = users.docs[0].id;
      }
    }

    // Create the order in Payload CMS
    const order = await payload.create({
      collection: 'orders',
      data: {
        orderNumber: '', // will be auto-generated by hook
        customer: customerId ? customerId : undefined,
        customerInfo: {
          firstName: customerInfo.firstName,
          lastName: customerInfo.lastName,
          email: customerInfo.email,
          phone: customerInfo.phone,
          address: customerInfo.address,
          district: customerInfo.district,
          isCorporate: customerInfo.isCorporate || false,
          companyName: customerInfo.companyName,
          taxOffice: customerInfo.taxOffice,
          taxNumber: customerInfo.taxNumber,
        },
        orderItems: validatedItems.map((item) => ({
          product: item.productId,
          quantity: item.quantity,
          price: item.realUnitPrice,
          options: item.options,
        })),
        totalAmount: finalCalculatedTotal,
        usedCoupon: couponCode || undefined,
        status: 'pending',
        paymentStatus: 'unpaid',
      },
    })

    // Prepare Iyzico Request
    const protocol = req.headers.get('x-forwarded-proto') || (req.url.startsWith('https') ? 'https' : 'http');
    let hostHeader = req.headers.get('x-forwarded-host') || req.headers.get('host') || 'localhost:3000';
    let host = process.env.NEXT_PUBLIC_SITE_URL || `${protocol}://${hostHeader}`;
    if (!host.startsWith('http')) host = `https://${host}`;
    host = host.endsWith('/') ? host.slice(0, -1) : host;
    
    // Geliştirme ortamında (localhost) Iyzico'yu atla ve direkt başarılı say.
    if (process.env.NODE_ENV !== 'production' || host.includes('localhost')) {
      await payload.update({
        collection: 'orders',
        id: order.id,
        data: { paymentStatus: 'paid' },
      });
      return NextResponse.json({ 
        success: true, 
        orderNumber: order.orderNumber,
        paymentPageUrl: `/odeme/basarili?orderId=${order.id}`
      });
    }
    
    let formattedPhone = customerInfo.phone.replace(/\D/g, '');
    if (formattedPhone.startsWith('0')) formattedPhone = formattedPhone.substring(1);
    if (formattedPhone.length === 10) formattedPhone = '+90' + formattedPhone;
    else if (!formattedPhone.startsWith('+')) formattedPhone = '+' + formattedPhone;

    const safeAddress = `${customerInfo.district} - ${customerInfo.address}`.padEnd(10, ' ').substring(0, 250);

    // --- IYZICO IPTAL (MOCK EKRAN ICIN) ---
    return NextResponse.json({ 
      success: true, 
      isMock: true,
      amount: finalCalculatedTotal,
      orderId: order.id,
      orderNumber: order.orderNumber
    });

    /*
    const request = {
      locale: 'tr',
      conversationId: order.orderNumber, // hook tarafından oluşturulan numara
      price: calculatedTotal.toString(),
      paidPrice: calculatedTotal.toString(),
      currency: 'TRY',
      basketId: order.id.toString(),
      paymentGroup: 'PRODUCT',
      callbackUrl: `${host}/api/iyzico/callback`,
      enabledInstallments: [2, 3, 6, 9],
      buyer: {
        id: 'BY789',
        name: customerInfo.firstName || 'Bilinmiyor',
        surname: customerInfo.lastName || 'Bilinmiyor',
        gsmNumber: formattedPhone,
        email: customerInfo.email,
        identityNumber: (customerInfo.isCorporate && customerInfo.taxNumber) ? customerInfo.taxNumber : '11111111111', 
        lastLoginDate: new Date().toISOString().replace('T', ' ').substring(0, 19),
        registrationDate: new Date().toISOString().replace('T', ' ').substring(0, 19),
        registrationAddress: safeAddress,
        ip: req.headers.get('x-forwarded-for') || '85.34.78.112',
        city: customerInfo.city,
        country: 'Turkey',
        zipCode: customerInfo.zipCode || '34000'
      },
      shippingAddress: {
        contactName: `${customerInfo.firstName} ${customerInfo.lastName}`,
        city: customerInfo.city,
        country: 'Turkey',
        address: safeAddress,
        zipCode: customerInfo.zipCode || '34000'
      },
      billingAddress: {
        contactName: customerInfo.isCorporate ? customerInfo.companyName : `${customerInfo.firstName} ${customerInfo.lastName}`,
        city: customerInfo.city,
        country: 'Turkey',
        address: safeAddress,
        zipCode: customerInfo.zipCode || '34000'
      },
      basketItems: validatedItems.map((item) => ({
        id: item.id,
        name: item.name,
        category1: 'Pastane',
        itemType: 'PHYSICAL',
        price: item.realLineTotal.toString()
      }))
    };

    console.log("Iyzico Request:", JSON.stringify(request, null, 2))

    const result = await initializeCheckoutForm(request);
    console.log("Iyzico Response:", JSON.stringify(result, null, 2))

    if (result.status === 'success') {
      return NextResponse.json({ 
        success: true, 
        orderNumber: order.orderNumber,
        checkoutFormContent: result.checkoutFormContent,
        paymentPageUrl: result.paymentPageUrl
      })
    } else {
      console.error("Iyzico Error:", result);
      return NextResponse.json({ 
        success: false, 
        error: result.errorMessage,
        errorCode: result.errorCode
      }, { status: 400 })
    }
    */

  } catch (error: any) {
    console.error('Ödeme başlatma hatası:', error)
    return NextResponse.json(
      { success: false, error: error.message || 'Ödeme başlatılamadı' },
      { status: 500 }
    )
  }
}
